#pragma warning disable SA1309 // Field names should not begin with underscore
#pragma warning disable SA1600 // Elements should be documented
#pragma warning disable SA1633 // The file header is missing
#pragma warning disable SA1518 // File is required to end with a single newline character
#pragma warning disable SA1028 // Code should not contain trailing whitespace
#pragma warning disable SA1513 // Closing brace should be followed by blank line
#pragma warning disable SA1402 // File may only contain a single type

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BoardGames.Api.Controllers;
using BoardGames.Api.Services;
using BoardGames.Data;
using BoardGames.Data.Models;
using BoardGames.Data.Repositories;
using BoardGames.Shared.DTO;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Xunit;

namespace BoardGames.WebTests.IntegrationTests
{
    [Collection("SharedDatabase")]
    public class ChatMessagingIntegrationTests
    {
        private readonly SharedDatabaseFixture _fixture;

        public ChatMessagingIntegrationTests(SharedDatabaseFixture fixture)
        {
            _fixture = fixture;
        }

        private async Task<(ConversationApiService Service, ConversationController Controller)> CreateTestSubject(IServiceScope scope)
        {
            var dbFactory = scope.ServiceProvider.GetRequiredService<IDbContextFactory<AppDbContext>>();
            var setupDb = dbFactory.CreateDbContext();

            // ConversationApiService and AccountRepository are tightly coupled to the DB
            var accountRepo = new AccountRepository(dbFactory);
            var conversationRepo = new ConversationRepository(setupDb);
            var service = new ConversationApiService(conversationRepo, accountRepo);
            var controller = new ConversationController(service);

            return (service, controller);
        }

        [Fact]
        public async Task SendMessage_WithValidData_WritesToDatabaseCorrectly()
        {
            // Arrange
            using var scope = _fixture.Factory.Services.CreateScope();
            var dbFactory = scope.ServiceProvider.GetRequiredService<IDbContextFactory<AppDbContext>>();
            using var db = dbFactory.CreateDbContext();

            var sender = await db.Users.FirstAsync(u => u.PamUserId == 200);
            var receiver = await db.Users.FirstAsync(u => u.PamUserId == 201);

            // Create a dedicated conversation for this test
            var conversation = new Conversation
            {
                Participants = new List<ConversationParticipant>
                {
                    new ConversationParticipant { UserId = sender.PamUserId },
                    new ConversationParticipant { UserId = receiver.PamUserId }
                }
            };
            db.Conversations.Add(conversation);
            await db.SaveChangesAsync();

            var (_, controller) = await CreateTestSubject(scope);

            var messageDto = new MessageDataTransferObject(
                Id: 0,
                ConversationId: conversation.ConversationId,
                SenderId: sender.PamUserId,
                ReceiverId: receiver.PamUserId,
                SentAt: DateTime.UtcNow,
                Content: "Hello World!",
                Type: MessageType.MessageText,
                ImageUrl: string.Empty,
                IsResolved: false,
                IsAccepted: false,
                IsAcceptedByBuyer: false,
                IsAcceptedBySeller: false,
                RequestId: -1,
                PaymentId: -1,
                RentalId: -1
            );

            // Act
            var result = await controller.SendMessage(messageDto);

            // Assert
            var okResult = Assert.IsType<OkObjectResult>(result.Result);
            var persistedDto = Assert.IsType<MessageDataTransferObject>(okResult.Value);

            Assert.True(persistedDto.Id > 0, "Message ID should be auto-generated by the database.");
            Assert.Equal("Hello World!", persistedDto.Content);

            using var assertDb = dbFactory.CreateDbContext();
            var savedMessage = await assertDb.Messages.OfType<TextMessage>().FirstOrDefaultAsync(m => m.MessageId == persistedDto.Id);
            
            Assert.NotNull(savedMessage);
            Assert.Equal(conversation.ConversationId, savedMessage.ConversationId);
            Assert.Equal(sender.PamUserId, savedMessage.MessageSenderId);
            Assert.Equal("Hello World!", savedMessage.TextMessageContent);
        }

        [Fact]
        public async Task SendMessage_WithEmptyContent_ReturnsBadRequest()
        {
            // Arrange
            using var scope = _fixture.Factory.Services.CreateScope();
            var dbFactory = scope.ServiceProvider.GetRequiredService<IDbContextFactory<AppDbContext>>();
            using var db = dbFactory.CreateDbContext();

            var sender = await db.Users.FirstAsync(u => u.PamUserId == 200);
            var receiver = await db.Users.FirstAsync(u => u.PamUserId == 201);

            var conversation = new Conversation
            {
                Participants = new List<ConversationParticipant>
                {
                    new ConversationParticipant { UserId = sender.PamUserId },
                    new ConversationParticipant { UserId = receiver.PamUserId }
                }
            };
            db.Conversations.Add(conversation);
            await db.SaveChangesAsync();

            var (_, controller) = await CreateTestSubject(scope);

            var messageDto = new MessageDataTransferObject(
                0, conversation.ConversationId, sender.PamUserId, receiver.PamUserId, DateTime.UtcNow,
                "   ", // Empty/whitespace string
                MessageType.MessageText, string.Empty, false, false, false, false, -1, -1, -1);

            // Act
            var result = await controller.SendMessage(messageDto);

            // Assert
            var badRequest = Assert.IsType<BadRequestObjectResult>(result.Result);
            Assert.Contains("empty", badRequest.Value?.ToString(), StringComparison.OrdinalIgnoreCase);
        }

        [Fact]
        public async Task SendMessage_ToNonExistentConversation_ReturnsNotFound()
        {
            // Arrange
            using var scope = _fixture.Factory.Services.CreateScope();
            var dbFactory = scope.ServiceProvider.GetRequiredService<IDbContextFactory<AppDbContext>>();
            using var db = dbFactory.CreateDbContext();

            var sender = await db.Users.FirstAsync(u => u.PamUserId == 200);
            var receiver = await db.Users.FirstAsync(u => u.PamUserId == 201);

            var (_, controller) = await CreateTestSubject(scope);

            int nonExistentConversationId = 999999;
            var messageDto = new MessageDataTransferObject(
                0, nonExistentConversationId, sender.PamUserId, receiver.PamUserId, DateTime.UtcNow,
                "Ghost message", MessageType.MessageText, string.Empty, false, false, false, false, -1, -1, -1);

            // Act
            var result = await controller.SendMessage(messageDto);

            // Assert
            Assert.IsType<NotFoundResult>(result.Result);
        }

        [Fact]
        public async Task SendMessage_FromSuspendedUser_ReturnsForbidden()
        {
            // Arrange
            using var scope = _fixture.Factory.Services.CreateScope();
            var dbFactory = scope.ServiceProvider.GetRequiredService<IDbContextFactory<AppDbContext>>();
            using var db = dbFactory.CreateDbContext();

            // Create a new suspended user for this test
            var suspendedUser = new User 
            { 
                Id = Guid.NewGuid(), 
                PamUserId = 202, 
                Username = "suspended_user",
                DisplayName = "Suspended User", 
                Email = "suspended@test.com", 
                PasswordHash = "hash",
                Country = "TestCountry",
                City = "TestCity",
                IsSuspended = true
            };
            var receiver = await db.Users.FirstAsync(u => u.PamUserId == 201);

            db.Users.Add(suspendedUser);
            
            var conversation = new Conversation
            {
                Participants = new List<ConversationParticipant>
                {
                    new ConversationParticipant { UserId = suspendedUser.PamUserId },
                    new ConversationParticipant { UserId = receiver.PamUserId }
                }
            };
            db.Conversations.Add(conversation);
            await db.SaveChangesAsync();

            var (_, controller) = await CreateTestSubject(scope);

            var messageDto = new MessageDataTransferObject(
                0, conversation.ConversationId, suspendedUser.PamUserId, receiver.PamUserId, DateTime.UtcNow,
                "I shouldn't be able to send this", MessageType.MessageText, string.Empty, false, false, false, false, -1, -1, -1);

            // Act
            var result = await controller.SendMessage(messageDto);

            // Assert
            var objectResult = Assert.IsType<ObjectResult>(result.Result);
            Assert.Equal(403, objectResult.StatusCode);
            Assert.Contains("suspended", objectResult.Value?.ToString(), StringComparison.OrdinalIgnoreCase);
        }
    }
}
