// <auto-generated />
using System;
using BookingBoardGames.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookingBoardGames.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("City", builderCity =>
                {
                    builderCity.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(builderCity.Property<int>("CityId"));

                    builderCity.Property<double>("Latitude")
                        .HasColumnType("float")
                        .HasColumnName("latitude");

                    builderCity.Property<double>("Longitude")
                        .HasColumnType("float")
                        .HasColumnName("longitude");

                    builderCity.Property<string>("MainName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("main_name");

                    builderCity.Property<string>("Names")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("names");

                    builderCity.HasKey("CityId");

                    builderCity.ToTable("cities");
                });

            modelBuilder.Entity("Conversation", builderConversation =>
                {
                    builderConversation.Property<int>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(builderConversation.Property<int>("ConversationId"));

                    builderConversation.HasKey("ConversationId");

                    builderConversation.ToTable("conversations");
                });

            modelBuilder.Entity("ConversationParticipant", builderConversationParticipant =>
                {
                    builderConversationParticipant.Property<int>("ConversationId")
                        .HasColumnType("int")
                        .HasColumnName("conversation_id");

                    builderConversationParticipant.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    builderConversationParticipant.Property<DateTime?>("LastMessageReadTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_message_read_time");

                    builderConversationParticipant.Property<int>("UnreadMessagesCount")
                        .HasColumnType("int")
                        .HasColumnName("unread_messages_count");

                    builderConversationParticipant.HasKey("ConversationId", "UserId");
                    builderConversationParticipant.HasIndex("UserId");

                    builderConversationParticipant.ToTable("conversation_participants");
                });

            modelBuilder.Entity("Game", builderGame =>
                {
                    builderGame.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(builderGame.Property<int>("Id"));

                    builderGame.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    builderGame.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("image");

                    builderGame.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    builderGame.Property<int>("MaximumPlayerNumber")
                        .HasColumnType("int")
                        .HasColumnName("maximum_player_number");

                    builderGame.Property<int>("MinimumPlayerNumber")
                        .HasColumnType("int")
                        .HasColumnName("minimum_player_number");

                    builderGame.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    builderGame.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("owner_id");

                    builderGame.Property<decimal>("PricePerDay")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    builderGame.HasKey("Id");

                    builderGame.HasIndex("OwnerId");

                    builderGame.ToTable("games");
                });

            modelBuilder.Entity("Message", builderMessage =>
                {
                    builderMessage.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(builderMessage.Property<int>("MessageId"));

                    builderMessage.Property<int>("ConversationId")
                        .HasColumnType("int")
                        .HasColumnName("conversation_id");

                    builderMessage.Property<string>("MessageCategory")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    builderMessage.Property<string>("MessageContentAsString")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message_content_as_string");

                    builderMessage.Property<int>("MessageReceiverId")
                        .HasColumnType("int")
                        .HasColumnName("message_receiver_id");

                    builderMessage.Property<int>("MessageSenderId")
                        .HasColumnType("int")
                        .HasColumnName("message_sender_id");

                    builderMessage.Property<DateTime>("MessageSentTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("message_sent_time");

                    builderMessage.HasKey("MessageId");
                    builderMessage.HasIndex("ConversationId");

                    builderMessage.HasIndex("MessageReceiverId");

                    builderMessage.HasIndex("MessageSenderId");

                    builderMessage.ToTable("messages");

                    builderMessage.HasDiscriminator<string>("MessageCategory").HasValue("Message");

                    builderMessage.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Payment", builderPayment =>
                {
                    builderPayment.Property<int>("TransactionIdentifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(builderPayment.Property<int>("TransactionIdentifier"));

                    builderPayment.Property<int>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("client_id");

                    builderPayment.Property<DateTime?>("DateConfirmedBuyer")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_confirmed_buyer");

                    builderPayment.Property<DateTime?>("DateConfirmedSeller")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_confirmed_seller");

                    builderPayment.Property<DateTime?>("DateOfTransaction")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_of_transaction");

                    builderPayment.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("owner_id");

                    builderPayment.Property<decimal>("PaidAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("paid_amount");

                    builderPayment.Property<string>("PaymentCategory")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    builderPayment.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("payment_method");

                    builderPayment.Property<int>("PaymentState")
                        .HasColumnType("int")
                        .HasColumnName("payment_state");

                    builderPayment.Property<string>("ReceiptFilePath")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("receipt_file_path");

                    builderPayment.Property<int>("RequestId")
                        .HasColumnType("int")
                        .HasColumnName("request_id");

                    builderPayment.HasKey("TransactionIdentifier");
                    builderPayment.HasIndex("ClientId");

                    builderPayment.HasIndex("OwnerId");

                    builderPayment.HasIndex("RequestId");

                    builderPayment.ToTable("payments");

                    builderPayment.HasDiscriminator<string>("PaymentCategory").HasValue("Standard");
                    builderPayment.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Rental", builderRental =>
                {
                    builderRental.Property<int>("RentalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(builderRental.Property<int>("RentalId"));

                    builderRental.Property<int>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("client_id");

                    builderRental.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_date");

                    builderRental.Property<int>("GameId")
                        .HasColumnType("int")
                        .HasColumnName("game_id");

                    builderRental.Property<int>("OwnerId")
                        .HasColumnType("int")
                        .HasColumnName("owner_id");

                    builderRental.Property<int?>("PaymentTransactionIdentifier")
                        .HasColumnType("int");

                    builderRental.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_date");

                    builderRental.Property<decimal?>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_price");

                    builderRental.HasKey("RentalId");

                    builderRental.HasIndex("ClientId");

                    builderRental.HasIndex("GameId");
                    builderRental.HasIndex("OwnerId");

                    builderRental.HasIndex("PaymentTransactionIdentifier");

                    builderRental.ToTable("rentals");
                });

            modelBuilder.Entity("User", builderUser =>
                {
                    builderUser.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(builderUser.Property<int>("Id"));

                    builderUser.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("avatar_url");

                    builderUser.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("balance");

                    builderUser.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("city");

                    builderUser.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("country");

                    builderUser.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    builderUser.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("display_name");

                    builderUser.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    builderUser.Property<bool>("IsSuspended")
                        .HasColumnType("bit")
                        .HasColumnName("is_suspended");

                    builderUser.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    builderUser.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone_number");

                    builderUser.Property<string>("Street")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("street");

                    builderUser.Property<string>("StreetNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("street_number");

                    builderUser.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    builderUser.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("username");

                    builderUser.HasKey("Id");

                    builderUser.ToTable("users");
                });

            modelBuilder.Entity("CashAgreementMessage", builderCashAgreementMessage =>
                {
                    builderCashAgreementMessage.HasBaseType("Message");

                    builderCashAgreementMessage.Property<int>("CashPaymentId")
                        .HasColumnType("int")
                        .HasColumnName("cash_payment_id");

                    builderCashAgreementMessage.Property<bool>("IsCashAgreementAcceptedByBuyer")
                        .HasColumnType("bit")
                        .HasColumnName("is_cash_agreement_accepted_by_buyer");

                    builderCashAgreementMessage.Property<bool>("IsCashAgreementAcceptedBySeller")
                        .HasColumnType("bit")
                        .HasColumnName("is_cash_agreement_accepted_by_seller");

                    builderCashAgreementMessage.Property<bool>("IsCashAgreementResolved")
                        .HasColumnType("bit")
                        .HasColumnName("is_cash_agreement_resolved");

                    builderCashAgreementMessage.HasIndex("CashPaymentId");
                    builderCashAgreementMessage.ToTable("messages");

                    builderCashAgreementMessage.HasDiscriminator().HasValue("CashAgreement");
                });

            modelBuilder.Entity("ImageMessage", builderImageMessage =>
                {
                    builderImageMessage.HasBaseType("Message");

                    builderImageMessage.Property<string>("MessageImageUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message_image_url");

                    builderImageMessage.ToTable("messages");
                    builderImageMessage.HasDiscriminator().HasValue("Image");
                });

            modelBuilder.Entity("RentalRequestMessage", builderRentalRequestMessage =>
                {
                    builderRentalRequestMessage.HasBaseType("Message");

                    builderRentalRequestMessage.Property<bool>("IsRequestAccepted")
                        .HasColumnType("bit")
                        .HasColumnName("is_request_accepted");

                    builderRentalRequestMessage.Property<bool>("IsRequestResolved")
                        .HasColumnType("bit")
                        .HasColumnName("is_request_resolved");

                    builderRentalRequestMessage.Property<int>("RentalRequestId")
                        .HasColumnType("int")
                        .HasColumnName("rental_request_id");

                    builderRentalRequestMessage.Property<string>("RequestContent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("request_content");

                    builderRentalRequestMessage.HasIndex("RentalRequestId");
                    builderRentalRequestMessage.ToTable("messages");

                    builderRentalRequestMessage.HasDiscriminator().HasValue("RentalRequest");
                });

            modelBuilder.Entity("SystemMessage", builderSystemMessage =>
                {
                    builderSystemMessage.HasBaseType("Message");

                    builderSystemMessage.Property<string>("MessageContent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("message_content");

                    builderSystemMessage.ToTable("messages");
                    builderSystemMessage.HasDiscriminator().HasValue("System");
                });

            modelBuilder.Entity("TextMessage", builderTextMessage =>
                {
                    builderTextMessage.HasBaseType("Message");

                    builderTextMessage.Property<string>("TextMessageContent")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("text_message_content");

                    builderTextMessage.ToTable("messages");
                    builderTextMessage.HasDiscriminator().HasValue("Text");
                });

            modelBuilder.Entity("HistoryPayment", builderHistoryPayment =>
                {
                    builderHistoryPayment.HasBaseType("Payment");

                    builderHistoryPayment.Property<string>("GameName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("game_name");

                    builderHistoryPayment.Property<string>("OwnerName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("owner_name");

                    builderHistoryPayment.ToTable("payments");
                    builderHistoryPayment.HasDiscriminator().HasValue("History");
                });

            modelBuilder.Entity("ConversationParticipant", builderConversationParticipant =>
                {
                    builderConversationParticipant.HasOne("Conversation", "Conversation")
                        .WithMany("Participants")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    builderConversationParticipant.HasOne("User", "User")
                        .WithMany("Conversations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    builderConversationParticipant.Navigation("Conversation");

                    builderConversationParticipant.Navigation("User");
                });

            modelBuilder.Entity("Game", builderGame =>
                {
                    builderGame.HasOne("User", "Owner")
                        .WithMany("OwnedGames")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    builderGame.Navigation("Owner");
                });

            modelBuilder.Entity("Message", builderMessage =>
                {
                    builderMessage.HasOne("Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    builderMessage.HasOne("User", "Receiver")
                        .WithMany()
                        .HasForeignKey("MessageReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    builderMessage.HasOne("User", "Sender")
                        .WithMany()
                        .HasForeignKey("MessageSenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    builderMessage.Navigation("Conversation");

                    builderMessage.Navigation("Receiver");

                    builderMessage.Navigation("Sender");
                });

            modelBuilder.Entity("Payment", builderPayment =>
                {
                    builderPayment.HasOne("User", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    builderPayment.HasOne("User", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    builderPayment.HasOne("Rental", "Request")
                        .WithMany()
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    builderPayment.Navigation("Client");

                    builderPayment.Navigation("Owner");

                    builderPayment.Navigation("Request");
                });

            modelBuilder.Entity("Rental", builderRental =>
                {
                    builderRental.HasOne("User", "Client")
                        .WithMany("RentalsAsClient")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    builderRental.HasOne("Game", "Game")
                        .WithMany("Rentals")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    builderRental.HasOne("User", "Owner")
                        .WithMany("RentalsAsOwner")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    builderRental.HasOne("Payment", "Payment")
                        .WithMany()
                        .HasForeignKey("PaymentTransactionIdentifier");

                    builderRental.Navigation("Client");
                    builderRental.Navigation("Game");

                    builderRental.Navigation("Owner");

                    builderRental.Navigation("Payment");
                });

            modelBuilder.Entity("CashAgreementMessage", builderCashAgreementMessage =>
                {
                    builderCashAgreementMessage.HasOne("Payment", "CashPayment")
                        .WithMany()
                        .HasForeignKey("CashPaymentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    builderCashAgreementMessage.Navigation("CashPayment");
                });

            modelBuilder.Entity("RentalRequestMessage", builderRentalRequestMessage =>
                {
                    builderRentalRequestMessage.HasOne("Rental", "RentalRequest")
                        .WithMany("Messages")
                        .HasForeignKey("RentalRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    builderRentalRequestMessage.Navigation("RentalRequest");
                });

            modelBuilder.Entity("Conversation", builderConversation =>
                {
                    builderConversation.Navigation("Messages");

                    builderConversation.Navigation("Participants");
                });

            modelBuilder.Entity("Game", builderGame =>
                {
                    builderGame.Navigation("Rentals");
                });

            modelBuilder.Entity("Rental", builderRental =>
                {
                    builderRental.Navigation("Messages");
                });

            modelBuilder.Entity("User", builderUser =>
                {
                    builderUser.Navigation("Conversations");

                    builderUser.Navigation("OwnedGames");
                    builderUser.Navigation("RentalsAsClient");

                    builderUser.Navigation("RentalsAsOwner");
                });
#pragma warning restore 612, 618
        }
    }
}
